# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\01.CORAL\11.LABEL\label\label.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(816, 576)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bt_browser = QtWidgets.QPushButton(self.centralwidget)
        self.bt_browser.setGeometry(QtCore.QRect(650, 410, 121, 23))
        self.bt_browser.setObjectName("bt_browser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(670, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.bt_print = QtWidgets.QPushButton(self.centralwidget)
        self.bt_print.setGeometry(QtCore.QRect(650, 450, 121, 23))
        self.bt_print.setObjectName("bt_print")
        self.data_browser = QtWidgets.QLineEdit(self.centralwidget)
        self.data_browser.setGeometry(QtCore.QRect(40, 410, 601, 20))
        self.data_browser.setObjectName("data_browser")
        self.data_posothta = QtWidgets.QLineEdit(self.centralwidget)
        self.data_posothta.setGeometry(QtCore.QRect(590, 450, 51, 20))
        self.data_posothta.setObjectName("data_posothta")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(510, 450, 71, 21))
        self.label_2.setObjectName("label_2")
        self.data_paratirisis = QtWidgets.QLineEdit(self.centralwidget)
        self.data_paratirisis.setGeometry(QtCore.QRect(182, 330, 551, 20))
        self.data_paratirisis.setObjectName("data_paratirisis")
        self.data_10 = QtWidgets.QLabel(self.centralwidget)
        self.data_10.setGeometry(QtCore.QRect(30, 330, 169, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.data_10.setFont(font)
        self.data_10.setObjectName("data_10")
        self.bt_green = QtWidgets.QPushButton(self.centralwidget)
        self.bt_green.setGeometry(QtCore.QRect(650, 490, 121, 23))
        self.bt_green.setObjectName("bt_green")
        self.bt_about = QtWidgets.QPushButton(self.centralwidget)
        self.bt_about.setGeometry(QtCore.QRect(650, 370, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.bt_about.setFont(font)
        self.bt_about.setObjectName("bt_about")
        self.line_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(300, 30, 151, 22))
        self.line_8.setObjectName("line_8")
        self.data_11 = QtWidgets.QLabel(self.centralwidget)
        self.data_11.setGeometry(QtCore.QRect(150, 30, 151, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.data_11.setFont(font)
        self.data_11.setObjectName("data_11")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(529, 70, 201, 52))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.data_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.data_8.setFont(font)
        self.data_8.setObjectName("data_8")
        self.gridLayout_2.addWidget(self.data_8, 0, 0, 1, 1)
        self.data_aa = QtWidgets.QLineEdit(self.layoutWidget)
        self.data_aa.setObjectName("data_aa")
        self.gridLayout_2.addWidget(self.data_aa, 0, 1, 1, 1)
        self.data_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.data_9.setFont(font)
        self.data_9.setObjectName("data_9")
        self.gridLayout_2.addWidget(self.data_9, 1, 0, 1, 1)
        self.data_count_aa = QtWidgets.QLineEdit(self.layoutWidget)
        self.data_count_aa.setObjectName("data_count_aa")
        self.gridLayout_2.addWidget(self.data_count_aa, 1, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(31, 71, 481, 221))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.data_1 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.data_1.setFont(font)
        self.data_1.setObjectName("data_1")
        self.gridLayout.addWidget(self.data_1, 0, 0, 1, 1)
        self.data_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.data_2.setFont(font)
        self.data_2.setObjectName("data_2")
        self.gridLayout.addWidget(self.data_2, 1, 0, 1, 1)
        self.data_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.data_3.setFont(font)
        self.data_3.setObjectName("data_3")
        self.gridLayout.addWidget(self.data_3, 2, 0, 1, 1)
        self.line_3 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 2, 1, 1, 2)
        self.data_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.data_4.setFont(font)
        self.data_4.setObjectName("data_4")
        self.gridLayout.addWidget(self.data_4, 3, 0, 1, 1)
        self.line_4 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 3, 1, 1, 2)
        self.data_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.data_5.setFont(font)
        self.data_5.setObjectName("data_5")
        self.gridLayout.addWidget(self.data_5, 4, 0, 1, 2)
        self.line_5 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 4, 2, 1, 1)
        self.data_6 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.data_6.setFont(font)
        self.data_6.setObjectName("data_6")
        self.gridLayout.addWidget(self.data_6, 5, 0, 1, 1)
        self.line_6 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 5, 2, 1, 1)
        self.data_7 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.data_7.setFont(font)
        self.data_7.setObjectName("data_7")
        self.gridLayout.addWidget(self.data_7, 6, 0, 1, 1)
        self.line_7 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 6, 2, 1, 1)
        self.line_1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.line_1.setObjectName("line_1")
        self.gridLayout.addWidget(self.line_1, 0, 2, 1, 1)
        self.line_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ΕΚΤΥΠΩΣΗ ΤΑΜΠΕΛΑΚΙΑ ΑΙΤΗΣΕΩΝ"))
        self.bt_browser.setText(_translate("MainWindow", "browser"))
        self.label.setText(_translate("MainWindow", "Α_ΤΜΗΜΑ"))
        self.bt_print.setText(_translate("MainWindow", "print"))
        self.data_posothta.setInputMask(_translate("MainWindow", "1"))
        self.label_2.setText(_translate("MainWindow", "ΠΟΣΟΤΗΤΑ"))
        self.data_10.setText(_translate("MainWindow", "ΠΑΡΑΤΗΡΗΣΕΙΣ:"))
        self.bt_green.setText(_translate("MainWindow", "GREEN"))
        self.bt_about.setText(_translate("MainWindow", "about   set printer"))
        self.data_11.setText(_translate("MainWindow", "ΟΝΟΜΑ ΑΡΧΕΙΟΥ:"))
        self.data_8.setText(_translate("MainWindow", "Σ. ΚΩΔΙΚΩΝ:"))
        self.data_9.setText(_translate("MainWindow", "Σ. ΤΕΜΑΧΙΩΝ:"))
        self.data_1.setText(_translate("MainWindow", "ΑΙΤΗΣΗ ΚΟΠΗΣ:"))
        self.data_2.setText(_translate("MainWindow", "ΑΡ. ΕΝΤΟΛΗΣ:"))
        self.data_3.setText(_translate("MainWindow", "ΤΟΜΕΑΣ:"))
        self.data_4.setText(_translate("MainWindow", "ΗΜΕΡ. ΑΙΤΗΣΗΣ:"))
        self.data_5.setText(_translate("MainWindow", "ΗΜΕΡ. ΠΑΡΑΔΟΣΗΣ:"))
        self.data_6.setText(_translate("MainWindow", "ΥΠΕΥΘΥΝΟΣ:"))
        self.data_7.setText(_translate("MainWindow", "ΠΑΡΑΔΟΣΗ:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
